# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Unix Installer

on:
  workflow_dispatch:
  release:
    types: [created]

env:
  VERSION_JFX: 19

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download JFX JMod Files
      uses: suisei-cn/actions-download-file@v1
      id: jfxjmods
      with:
        url: https://download2.gluonhq.com/openjfx/${{ env.VERSION_JFX }}/openjfx-${{ env.VERSION_JFX }}_linux-x64_bin-jmods.zip
        target: .
    - name: Decompress JFX JMod files
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        pathSource: ${{ steps.jfxjmods.outputs.filename }}
        pathTarget: ./demo/javafx
    - name: Normalize jmod folder
      run: mv ./demo/javafx/javafx-jmods-${{ env.VERSION_JFX }} ./demo/javafx/linux
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn -Dgpg.sign.skip=true -B clean install --file pom.xml
    - uses: actions/upload-artifact@v2
      with:
        name: graph-editor-demo.deb
        path: ./demo/target/*.deb
